name:                har
version:             0.1.0.0
github:              "idkravitz/har"
license:             GPL-3
author:              "Dmitry Kravtsov"
maintainer:          "idkravitz@gmail.com"
copyright:           "2020 Dmitry Kravtsov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/idkravitz/hdig#readme>

dependencies:
- base >= 4.7 && < 5
- binary >= 0.8
- bytestring >= 0.9
- array      >= 0.3
- filepath   >= 1.1

library:
  source-dirs: src

executables:
  hdig-exe:
    main:                har.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - har

#tests:
#  hdig-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - har
